# Generated by Django 2.2.14 on 2021-05-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Safety', 'Safety Materials'), ('Plumbing', 'Plumbing'), ('Electrical', 'Electrical'), ('Kitchen', 'Kitchen'), ('Flooring & Wall', 'Flooring & Walls'), ('Paints', 'Paints'), ('Tools & H.Ware', 'Tools & H.Ware')], max_length=20),
        ),
    ]
